// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYJVwXW51SRKYwBwLNZCHmjBxnte4Cuo',
    appId: '1:323483418354:web:abf2297344a5ff1ac0da6b',
    messagingSenderId: '323483418354',
    projectId: 'dindin-1c2a5',
    authDomain: 'dindin-1c2a5.firebaseapp.com',
    storageBucket: 'dindin-1c2a5.firebasestorage.app',
    measurementId: 'G-D7ECWJ22SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCur7j_7ZsT_3ICbJwLoMAiD0eTh4dCyII',
    appId: '1:323483418354:android:b37042193914b595c0da6b',
    messagingSenderId: '323483418354',
    projectId: 'dindin-1c2a5',
    storageBucket: 'dindin-1c2a5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKGWRFni8IUg-mrv4XJy5dECg6nNAcpY',
    appId: '1:323483418354:ios:1cd98871d079d69ec0da6b',
    messagingSenderId: '323483418354',
    projectId: 'dindin-1c2a5',
    storageBucket: 'dindin-1c2a5.firebasestorage.app',
    iosClientId: '323483418354-pt042qvuabfl6u7lpbte5jjmjob6ji93.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaFinanceiro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKGWRFni8IUg-mrv4XJy5dECg6nNAcpY',
    appId: '1:323483418354:ios:1cd98871d079d69ec0da6b',
    messagingSenderId: '323483418354',
    projectId: 'dindin-1c2a5',
    storageBucket: 'dindin-1c2a5.firebasestorage.app',
    iosClientId: '323483418354-pt042qvuabfl6u7lpbte5jjmjob6ji93.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbYJVwXW51SRKYwBwLNZCHmjBxnte4Cuo',
    appId: '1:323483418354:web:3cea6a947c8c018dc0da6b',
    messagingSenderId: '323483418354',
    projectId: 'dindin-1c2a5',
    authDomain: 'dindin-1c2a5.firebaseapp.com',
    storageBucket: 'dindin-1c2a5.firebasestorage.app',
    measurementId: 'G-73YFJ9FCVM',
  );
}
